stripe:
  is_test: true
  publish_key: pk_test_51LN6UlE5tkkKc9j7klJNin7W8j7N0ClyxPcWhQsjvSuvmyjurMxc1z9BkgLwjTiPyLE77IVSdg08wYAqGr7pQ3Bm00rTUWikVb
  private_key: sk_test_51LN6UlE5tkkKc9j7gBCTaDrZAs6rEHnFJ4VggyEXuJgMd455tCGMBwhcvdqP84WDIwfG7IS1efjNtaWXoseOBYTZ00UpBzUKIv
  webhook_key: stripe_test_webhook_key
  price_tables:
    plan: stripe_test_plan_price
